{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/10222","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/10222/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/10222/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/10222/events","html_url":"https://github.com/elastic/elasticsearch/issues/10222","id":63768625,"node_id":"MDU6SXNzdWU2Mzc2ODYyNQ==","number":10222,"title":"Java client instance doesn't recover from temporary ES unavailability ","user":{"login":"l15k4","id":518855,"node_id":"MDQ6VXNlcjUxODg1NQ==","avatar_url":"https://avatars1.githubusercontent.com/u/518855?v=4","gravatar_id":"","url":"https://api.github.com/users/l15k4","html_url":"https://github.com/l15k4","followers_url":"https://api.github.com/users/l15k4/followers","following_url":"https://api.github.com/users/l15k4/following{/other_user}","gists_url":"https://api.github.com/users/l15k4/gists{/gist_id}","starred_url":"https://api.github.com/users/l15k4/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/l15k4/subscriptions","organizations_url":"https://api.github.com/users/l15k4/orgs","repos_url":"https://api.github.com/users/l15k4/repos","events_url":"https://api.github.com/users/l15k4/events{/privacy}","received_events_url":"https://api.github.com/users/l15k4/received_events","type":"User","site_admin":false},"labels":[{"id":111416437,"node_id":"MDU6TGFiZWwxMTE0MTY0Mzc=","url":"https://api.github.com/repos/elastic/elasticsearch/labels/discuss","name":"discuss","color":"fbca04","default":false,"description":null}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2015-03-23T16:35:03Z","updated_at":"2015-12-05T20:51:32Z","closed_at":"2015-12-05T20:51:32Z","author_association":"NONE","active_lock_reason":null,"body":"Hey,\n\nI'm using ES 1.4.2 and it seems to me that if java client cannot temporarily ping node within `client.transport.ping_timeout` then it never manages to ping it again and [this happens](https://gist.github.com/l15k4/f40a115edb67c1fd4779)... Let say that I do a query from a different client (like Sense) that returns big result set, say `search?size=200000` that takes more than `client.transport.ping_timeout` then java client never recovers and a java client request that occurred within the unavailability never gets a response back... \n\nSo my solution to that was increasing `client.transport.ping_timeout`, but the problem with this now is that the transport client never returns response on that original request that occurred within the temporary unavailability...\n\nThis means a lot of \"resiliency\" coding on the java-client side ....\n\nBtw I tried that when `sniffing` was both enabled and disabled.\n","closed_by":{"login":"clintongormley","id":56599,"node_id":"MDQ6VXNlcjU2NTk5","avatar_url":"https://avatars0.githubusercontent.com/u/56599?v=4","gravatar_id":"","url":"https://api.github.com/users/clintongormley","html_url":"https://github.com/clintongormley","followers_url":"https://api.github.com/users/clintongormley/followers","following_url":"https://api.github.com/users/clintongormley/following{/other_user}","gists_url":"https://api.github.com/users/clintongormley/gists{/gist_id}","starred_url":"https://api.github.com/users/clintongormley/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/clintongormley/subscriptions","organizations_url":"https://api.github.com/users/clintongormley/orgs","repos_url":"https://api.github.com/users/clintongormley/repos","events_url":"https://api.github.com/users/clintongormley/events{/privacy}","received_events_url":"https://api.github.com/users/clintongormley/received_events","type":"User","site_admin":false},"performed_via_github_app":null}