{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/14989","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/14989/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/14989/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/14989/events","html_url":"https://github.com/elastic/elasticsearch/issues/14989","id":118720264,"node_id":"MDU6SXNzdWUxMTg3MjAyNjQ=","number":14989,"title":"After upgrade 2.0.0 -> 2.1.0 NoSuchFileException while deleting tlog files on *every* shard","user":{"login":"uschindler","id":1005388,"node_id":"MDQ6VXNlcjEwMDUzODg=","avatar_url":"https://avatars2.githubusercontent.com/u/1005388?v=4","gravatar_id":"","url":"https://api.github.com/users/uschindler","html_url":"https://github.com/uschindler","followers_url":"https://api.github.com/users/uschindler/followers","following_url":"https://api.github.com/users/uschindler/following{/other_user}","gists_url":"https://api.github.com/users/uschindler/gists{/gist_id}","starred_url":"https://api.github.com/users/uschindler/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/uschindler/subscriptions","organizations_url":"https://api.github.com/users/uschindler/orgs","repos_url":"https://api.github.com/users/uschindler/repos","events_url":"https://api.github.com/users/uschindler/events{/privacy}","received_events_url":"https://api.github.com/users/uschindler/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":{"login":"s1monw","id":973334,"node_id":"MDQ6VXNlcjk3MzMzNA==","avatar_url":"https://avatars0.githubusercontent.com/u/973334?v=4","gravatar_id":"","url":"https://api.github.com/users/s1monw","html_url":"https://github.com/s1monw","followers_url":"https://api.github.com/users/s1monw/followers","following_url":"https://api.github.com/users/s1monw/following{/other_user}","gists_url":"https://api.github.com/users/s1monw/gists{/gist_id}","starred_url":"https://api.github.com/users/s1monw/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/s1monw/subscriptions","organizations_url":"https://api.github.com/users/s1monw/orgs","repos_url":"https://api.github.com/users/s1monw/repos","events_url":"https://api.github.com/users/s1monw/events{/privacy}","received_events_url":"https://api.github.com/users/s1monw/received_events","type":"User","site_admin":false},"assignees":[{"login":"s1monw","id":973334,"node_id":"MDQ6VXNlcjk3MzMzNA==","avatar_url":"https://avatars0.githubusercontent.com/u/973334?v=4","gravatar_id":"","url":"https://api.github.com/users/s1monw","html_url":"https://github.com/s1monw","followers_url":"https://api.github.com/users/s1monw/followers","following_url":"https://api.github.com/users/s1monw/following{/other_user}","gists_url":"https://api.github.com/users/s1monw/gists{/gist_id}","starred_url":"https://api.github.com/users/s1monw/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/s1monw/subscriptions","organizations_url":"https://api.github.com/users/s1monw/orgs","repos_url":"https://api.github.com/users/s1monw/repos","events_url":"https://api.github.com/users/s1monw/events{/privacy}","received_events_url":"https://api.github.com/users/s1monw/received_events","type":"User","site_admin":false}],"milestone":null,"comments":16,"created_at":"2015-11-24T22:47:22Z","updated_at":"2016-02-05T07:11:25Z","closed_at":"2015-11-25T10:26:14Z","author_association":"CONTRIBUTOR","active_lock_reason":null,"body":"After upgrading a single node elasticsearch installation with 3 indexes, on startup Elasticsearch produces a message in the log file like the following:\n\n```\n[2015-11-24 22:36:38,840][WARN ][index.translog           ] [PANGAEA Elasticsearch] [portals_v1][1] failed to delete temp file /pangaea/elasticsearch/data/pangaea/nodes/0/indices/portals_v1/1/translog/translog-1417903832395804337.tlog\njava.nio.file.NoSuchFileException: /pangaea/elasticsearch/data/pangaea/nodes/0/indices/portals_v1/1/translog/translog-1417903832395804337.tlog\n        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)\n        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)\n        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)\n        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)\n        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)\n        at java.nio.file.Files.delete(Files.java:1126)\n        at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)\n        at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)\n        at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)\n        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)\n        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)\n        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)\n        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)\n        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)\n        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)\n        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)\n        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)\n        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n        at java.lang.Thread.run(Thread.java:745)\n```\n\nYou get one message per shard. The file really does not exist! The index works fine afterwards.\n\nIf you restart elasticsearch again the same errors occur again, but with different filenames.\n\nOperating system is Ubuntu 14.04; debian package installation:\nroot@pangaea-mw1:~# uname -a\nLinux pangaea-mw1 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux\n\nThis is not a blocker for me because everything works and I don't care about tranlog, but users that rely on it working may have problems.\n\nAll indexes were recreated a week ago with 2.0.0.\n","closed_by":{"login":"s1monw","id":973334,"node_id":"MDQ6VXNlcjk3MzMzNA==","avatar_url":"https://avatars0.githubusercontent.com/u/973334?v=4","gravatar_id":"","url":"https://api.github.com/users/s1monw","html_url":"https://github.com/s1monw","followers_url":"https://api.github.com/users/s1monw/followers","following_url":"https://api.github.com/users/s1monw/following{/other_user}","gists_url":"https://api.github.com/users/s1monw/gists{/gist_id}","starred_url":"https://api.github.com/users/s1monw/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/s1monw/subscriptions","organizations_url":"https://api.github.com/users/s1monw/orgs","repos_url":"https://api.github.com/users/s1monw/repos","events_url":"https://api.github.com/users/s1monw/events{/privacy}","received_events_url":"https://api.github.com/users/s1monw/received_events","type":"User","site_admin":false},"performed_via_github_app":null}