[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/255170790","html_url":"https://github.com/elastic/elasticsearch/issues/21038#issuecomment-255170790","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21038","id":255170790,"node_id":"MDEyOklzc3VlQ29tbWVudDI1NTE3MDc5MA==","user":{"login":"superhero","id":839818,"node_id":"MDQ6VXNlcjgzOTgxOA==","avatar_url":"https://avatars2.githubusercontent.com/u/839818?v=4","gravatar_id":"","url":"https://api.github.com/users/superhero","html_url":"https://github.com/superhero","followers_url":"https://api.github.com/users/superhero/followers","following_url":"https://api.github.com/users/superhero/following{/other_user}","gists_url":"https://api.github.com/users/superhero/gists{/gist_id}","starred_url":"https://api.github.com/users/superhero/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/superhero/subscriptions","organizations_url":"https://api.github.com/users/superhero/orgs","repos_url":"https://api.github.com/users/superhero/repos","events_url":"https://api.github.com/users/superhero/events{/privacy}","received_events_url":"https://api.github.com/users/superhero/received_events","type":"User","site_admin":false},"created_at":"2016-10-20T17:21:20Z","updated_at":"2016-10-20T17:21:20Z","author_association":"NONE","body":"There was more then one bug on the server, Elastic Search worked just fine even though the log is showing these exceptions..\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/373586323","html_url":"https://github.com/elastic/elasticsearch/issues/21038#issuecomment-373586323","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/21038","id":373586323,"node_id":"MDEyOklzc3VlQ29tbWVudDM3MzU4NjMyMw==","user":{"login":"dnhatn","id":13474362,"node_id":"MDQ6VXNlcjEzNDc0MzYy","avatar_url":"https://avatars3.githubusercontent.com/u/13474362?v=4","gravatar_id":"","url":"https://api.github.com/users/dnhatn","html_url":"https://github.com/dnhatn","followers_url":"https://api.github.com/users/dnhatn/followers","following_url":"https://api.github.com/users/dnhatn/following{/other_user}","gists_url":"https://api.github.com/users/dnhatn/gists{/gist_id}","starred_url":"https://api.github.com/users/dnhatn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dnhatn/subscriptions","organizations_url":"https://api.github.com/users/dnhatn/orgs","repos_url":"https://api.github.com/users/dnhatn/repos","events_url":"https://api.github.com/users/dnhatn/events{/privacy}","received_events_url":"https://api.github.com/users/dnhatn/received_events","type":"User","site_admin":false},"created_at":"2018-03-16T02:42:11Z","updated_at":"2018-03-16T02:42:11Z","author_association":"MEMBER","body":"Closing this because there has been no update (or similar reports) on this issue. Moreover, we have improved the resiliency of translog a lot recently.","performed_via_github_app":null}]