{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/23627","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/23627/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/23627/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/23627/events","html_url":"https://github.com/elastic/elasticsearch/issues/23627","id":214950380,"node_id":"MDU6SXNzdWUyMTQ5NTAzODA=","number":23627,"title":"search_phase_execution_exception - field [bbox] is not a geo_point field (using geo_shape)","user":{"login":"murdav","id":1561285,"node_id":"MDQ6VXNlcjE1NjEyODU=","avatar_url":"https://avatars3.githubusercontent.com/u/1561285?v=4","gravatar_id":"","url":"https://api.github.com/users/murdav","html_url":"https://github.com/murdav","followers_url":"https://api.github.com/users/murdav/followers","following_url":"https://api.github.com/users/murdav/following{/other_user}","gists_url":"https://api.github.com/users/murdav/gists{/gist_id}","starred_url":"https://api.github.com/users/murdav/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/murdav/subscriptions","organizations_url":"https://api.github.com/users/murdav/orgs","repos_url":"https://api.github.com/users/murdav/repos","events_url":"https://api.github.com/users/murdav/events{/privacy}","received_events_url":"https://api.github.com/users/murdav/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-03-17T09:31:08Z","updated_at":"2017-03-17T09:33:19Z","closed_at":"2017-03-17T09:32:37Z","author_association":"NONE","active_lock_reason":null,"body":"Dear All,\r\n\r\nI'm using: Elasticsearch version: 5.2\r\n\r\nMy index mapping contains:\r\n`'bbox': {'type': 'geo_shape', 'precision': '10km', 'tree': 'quadtree', },`\r\n\r\nA Python script inserts in Elastic the area_of_interest object fields, and the bbox insertion is:\r\n\r\n```\r\n        if area_of_interest.bbox_minx is not None:\r\n            doc['bbox'] = {\r\n                \"type\": \"envelope\",\r\n                \"coordinates\": [[obj.bbox_minx, obj.bbox_maxy], [obj.bbox_maxx, obj.bbox_miny]],\r\n            }\r\n        else:\r\n            doc['bbox'] = None\r\n```\r\n\r\nOf course all bbox fields (bbox_minx, bbox_maxy, bbox_maxx, bbox_miny) are evaluated or None (null in Elastic is inserted).\r\n\r\nThe insertion works:\r\n\r\n```\r\n# station with bbox evaluated\r\n{\r\n\t\"_index\": \"place-20170317-054435\",\r\n\t\"_type\": \"placelayer\",\r\n\t\"_id\": \"1962\",\r\n\t\"_version\": 1,\r\n\t\"found\": true,\r\n\t\"_source\": {\r\n\t\"id\": 1962,\r\n\t\"lang\": \"id\",\r\n\t\"bbox\": {\r\n\t\t\"type\": \"envelope\",\r\n\t\t\"coordinates\": [[-119.6928, 34.4031], [-119.6928,34.4031]]\r\n\t},\r\n\t\"modified\": \"2017-03-15T15:05:06.678083+00:00\",\r\n\t\"created\": \"2017-03-15T15:05:06.677892+00:00\",\r\n\t\"name\": \"station test 33333\",\r\n\t\"description\": \"desc station 33333\",\r\n\t}\r\n}\r\n\r\n# station with bbox to null\r\n{\r\n\t\"_index\": \"place-20170317-054435\",\r\n\t\"_type\": \"placelayer\",\r\n\t\"_id\": \"2390\",\r\n\t\"_version\": 1,\r\n\t\"found\": true,\r\n\t\"_source\": {\r\n\t\t\"id\": 2390,\r\n\t\t\"lang\": \"\",\r\n\t\t\"bbox\": null,\r\n\t\t\"modified\": \"2017-03-17T04:57:27.781646+00:00\",\r\n\t\t\"created\": \"2017-03-17T04:57:27.519688+00:00\",\r\n\t\t\"name\": \"station test 19383\",\r\n\t\t\"description\": \"desc station 19383\",\r\n\t}\r\n}\r\n\r\n```\r\n\r\nWhile querying I got this EXCEPTION:\r\n\r\n```\r\nGET /places/placelayer/_search\r\n{\r\n    \"query\": {\r\n        \"bool\" : {\r\n            \"must\" : {\r\n                \"match_all\" : {}\r\n            },\r\n            \"filter\" : {\r\n                \"geo_bounding_box\" : {\r\n                    \"bbox\" : {\r\n                        \"top_left\" : {\r\n                            \"lat\" : 40.73,\r\n                            \"lon\" : -74.1\r\n                        },\r\n                        \"bottom_right\" : {\r\n                            \"lat\" : 40.01,\r\n                            \"lon\" : -71.12\r\n                        }\r\n                    }\r\n                }\r\n            }\r\n        }\r\n    }\r\n}\r\n```\r\n\r\n```\r\nraise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\r\nelasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'field [bbox] is not a geo_point field')\r\n```\r\n\r\nMy field called bbox is a `'type': 'geo_shape'`,  and sincerely I don't understand the reason for the exception. \r\n\r\nThanks,\r\n\r\nD\r\n","closed_by":{"login":"dadoonet","id":274222,"node_id":"MDQ6VXNlcjI3NDIyMg==","avatar_url":"https://avatars3.githubusercontent.com/u/274222?v=4","gravatar_id":"","url":"https://api.github.com/users/dadoonet","html_url":"https://github.com/dadoonet","followers_url":"https://api.github.com/users/dadoonet/followers","following_url":"https://api.github.com/users/dadoonet/following{/other_user}","gists_url":"https://api.github.com/users/dadoonet/gists{/gist_id}","starred_url":"https://api.github.com/users/dadoonet/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dadoonet/subscriptions","organizations_url":"https://api.github.com/users/dadoonet/orgs","repos_url":"https://api.github.com/users/dadoonet/repos","events_url":"https://api.github.com/users/dadoonet/events{/privacy}","received_events_url":"https://api.github.com/users/dadoonet/received_events","type":"User","site_admin":false},"performed_via_github_app":null}