{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/29649","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/29649/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/29649/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/29649/events","html_url":"https://github.com/elastic/elasticsearch/issues/29649","id":316599062,"node_id":"MDU6SXNzdWUzMTY1OTkwNjI=","number":29649,"title":"Creating a snapshot fails at the very last stage with NullPointerException","user":{"login":"redlus","id":7827282,"node_id":"MDQ6VXNlcjc4MjcyODI=","avatar_url":"https://avatars3.githubusercontent.com/u/7827282?v=4","gravatar_id":"","url":"https://api.github.com/users/redlus","html_url":"https://github.com/redlus","followers_url":"https://api.github.com/users/redlus/followers","following_url":"https://api.github.com/users/redlus/following{/other_user}","gists_url":"https://api.github.com/users/redlus/gists{/gist_id}","starred_url":"https://api.github.com/users/redlus/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/redlus/subscriptions","organizations_url":"https://api.github.com/users/redlus/orgs","repos_url":"https://api.github.com/users/redlus/repos","events_url":"https://api.github.com/users/redlus/events{/privacy}","received_events_url":"https://api.github.com/users/redlus/received_events","type":"User","site_admin":false},"labels":[{"id":143077482,"node_id":"MDU6TGFiZWwxNDMwNzc0ODI=","url":"https://api.github.com/repos/elastic/elasticsearch/labels/:Distributed/Snapshot/Restore","name":":Distributed/Snapshot/Restore","color":"0e8a16","default":false,"description":"Anything directly related to the `_snapshot/*` APIs"},{"id":23173,"node_id":"MDU6TGFiZWwyMzE3Mw==","url":"https://api.github.com/repos/elastic/elasticsearch/labels/%3Ebug","name":">bug","color":"b60205","default":false,"description":null}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2018-04-22T17:53:13Z","updated_at":"2018-04-25T16:46:55Z","closed_at":"2018-04-24T08:49:44Z","author_association":"NONE","active_lock_reason":null,"body":"Hi,\r\n\r\nCreating a snapshot of a single index reports it finished correctly through _snapshot/_status (\"state\": \"SUCCESS\"), but a NullPointerException is thrown and the snapshot eventually does not show up in the repository.\r\n\r\nElasticsearch version:\r\n6.2.3\r\n\r\nPlugins installed:\r\ningest-attachment\r\ningest-geoip\r\nmapper-murmur3\r\nmapper-size\r\nrepository-azure\r\nrepository-gcs\r\nrepository-s3\r\n\r\nJVM version:\r\nopenjdk version \"1.8.0_151\"\r\nOpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)\r\nOpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)\r\n\r\nOS version:\r\nLinux 4.13.0-1011-azure #14-Ubuntu SMP 2018 x86_64 GNU/Linux\r\n\r\nDescription of the problem including expected versus actual behavior:\r\nWe've recently upgraded our elasticsearch cluster from v5.2.2 to v6.2.3, running both clusters in parallel and used the snapshots feature on Azure blob storage to replicate the data to the new cluster. After migration, new snapshot creation tasks are executed daily for backup from the new v6.2.3 cluster onto the same repositories. Initiating the create snapshots succeeds, taking the expected amount of time to copy the data to Azure and even reporting \"state\": \"SUCCESS\" on _snapshot/_status:\r\n\r\n> {\r\n    \"snapshots\": [\r\n        {\r\n            \"snapshot\": \"2_newlogs_20180328\",\r\n            \"repository\": \"2_newlogs\",\r\n            \"uuid\": \"ds3cBPQOSpqIOt53-ImKBw\",\r\n            \"state\": \"SUCCESS\",\r\n            \"include_global_state\": false,\r\n            \"shards_stats\": {\r\n                \"initializing\": 0,\r\n                \"started\": 0,\r\n                \"finalizing\": 0,\r\n                \"done\": 2,\r\n                \"failed\": 0,\r\n                \"total\": 2\r\n            },\r\n            \"stats\": {\r\n                \"number_of_files\": 147,\r\n                \"processed_files\": 147,\r\n                \"total_size_in_bytes\": 12541757401,\r\n                \"processed_size_in_bytes\": 12541757401,\r\n                \"start_time_in_millis\": 1524411697845,\r\n                \"time_in_millis\": 462463\r\n            },\r\n            \"indices\": {\r\n                \"2_newlogs_20180328-01\": {\r\n                    \"shards_stats\": {\r\n                        \"initializing\": 0,\r\n                        \"started\": 0,\r\n                        \"finalizing\": 0,\r\n                        \"done\": 2,\r\n                        \"failed\": 0,\r\n                        \"total\": 2\r\n                    },\r\n                    \"stats\": {\r\n                        \"number_of_files\": 147,\r\n                        \"processed_files\": 147,\r\n                        \"total_size_in_bytes\": 12541757401,\r\n                        \"processed_size_in_bytes\": 12541757401,\r\n                        \"start_time_in_millis\": 1524411697845,\r\n                        \"time_in_millis\": 462463\r\n                    },\r\n                    \"shards\": {\r\n                        \"0\": {\r\n                            \"stage\": \"DONE\",\r\n                            \"stats\": {\r\n                                \"number_of_files\": 63,\r\n                                \"processed_files\": 63,\r\n                                \"total_size_in_bytes\": 6270745558,\r\n                                \"processed_size_in_bytes\": 6270745558,\r\n                                \"start_time_in_millis\": 1524411697845,\r\n                                \"time_in_millis\": 439319\r\n                            }\r\n                        },\r\n                        \"1\": {\r\n                            \"stage\": \"DONE\",\r\n                            \"stats\": {\r\n                                \"number_of_files\": 84,\r\n                                \"processed_files\": 84,\r\n                                \"total_size_in_bytes\": 6271011843,\r\n                                \"processed_size_in_bytes\": 6271011843,\r\n                                \"start_time_in_millis\": 1524411697863,\r\n                                \"time_in_millis\": 462445\r\n                            }\r\n                        }\r\n                    }\r\n                }\r\n            }\r\n        }\r\n    ]\r\n}\r\n\r\nAfter the create snapshot finishes (_snapshot/_status returns an empty array), the snapshot does not show up in the repository and a NullPointerException is thrown in the master node logs:\r\n\r\n> [2018-04-22T15:49:20,567][WARN ][o.e.s.SnapshotsService   ] [prod-elasticsearch-master-003] [2_newlogs:2_newlogs_20180328/ds3cBPQOSpqIOt53-ImKBw] failed to finalize snapshot\r\njava.lang.NullPointerException: null\r\n    at org.elasticsearch.repositories.RepositoryData.snapshotsToXContent(RepositoryData.java:341) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]\r\n    at org.elasticsearch.repositories.blobstore.BlobStoreRepository.writeIndexGen(BlobStoreRepository.java:674) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]\r\n    at org.elasticsearch.repositories.blobstore.BlobStoreRepository.finalizeSnapshot(BlobStoreRepository.java:470) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]\r\n    at org.elasticsearch.snapshots.SnapshotsService.lambda$endSnapshot$3(SnapshotsService.java:974) ~[elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]\r\n    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.4-SNAPSHOT.jar:6.2.4-SNAPSHOT]\r\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]\r\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]\r\n    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]\r\n\r\nThis has been replicated with multiple create snapshots operations on multiple repositories.\r\nAdditionally, deleting the repository (without individually deleting the snapshots it contains) and re-creating it (thereby loading the available snapshots from 5.2.2) did not solve the problem.\r\n\r\nI'd be happy to provide any additional information as needed.\r\n\r\nThanks!","closed_by":{"login":"colings86","id":236731,"node_id":"MDQ6VXNlcjIzNjczMQ==","avatar_url":"https://avatars0.githubusercontent.com/u/236731?v=4","gravatar_id":"","url":"https://api.github.com/users/colings86","html_url":"https://github.com/colings86","followers_url":"https://api.github.com/users/colings86/followers","following_url":"https://api.github.com/users/colings86/following{/other_user}","gists_url":"https://api.github.com/users/colings86/gists{/gist_id}","starred_url":"https://api.github.com/users/colings86/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/colings86/subscriptions","organizations_url":"https://api.github.com/users/colings86/orgs","repos_url":"https://api.github.com/users/colings86/repos","events_url":"https://api.github.com/users/colings86/events{/privacy}","received_events_url":"https://api.github.com/users/colings86/received_events","type":"User","site_admin":false},"performed_via_github_app":null}