{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/30391","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/30391/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/30391/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/30391/events","html_url":"https://github.com/elastic/elasticsearch/issues/30391","id":320273803,"node_id":"MDU6SXNzdWUzMjAyNzM4MDM=","number":30391,"title":"Failures occurs while inserted data in ElaticSearch : failure in bulk execution","user":{"login":"rajibhalder","id":21025998,"node_id":"MDQ6VXNlcjIxMDI1OTk4","avatar_url":"https://avatars3.githubusercontent.com/u/21025998?v=4","gravatar_id":"","url":"https://api.github.com/users/rajibhalder","html_url":"https://github.com/rajibhalder","followers_url":"https://api.github.com/users/rajibhalder/followers","following_url":"https://api.github.com/users/rajibhalder/following{/other_user}","gists_url":"https://api.github.com/users/rajibhalder/gists{/gist_id}","starred_url":"https://api.github.com/users/rajibhalder/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rajibhalder/subscriptions","organizations_url":"https://api.github.com/users/rajibhalder/orgs","repos_url":"https://api.github.com/users/rajibhalder/repos","events_url":"https://api.github.com/users/rajibhalder/events{/privacy}","received_events_url":"https://api.github.com/users/rajibhalder/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-04T13:24:20Z","updated_at":"2018-05-04T15:17:42Z","closed_at":"2018-05-04T15:17:42Z","author_association":"NONE","active_lock_reason":null,"body":"We are getting the below error from elastic search while my application is running in a multi threaded environment and number of threads are almost 25:\r\n\r\n>  2018-05-01 17:56:57,802 ERROR [com.sicap.targetme.svc.utils.SimpleDelayQueueChannel] (STC-Consumer-Threadpool-62715 2018-05-01 17:56:56.652 MSISDN: 966503236382, CAMPAIGN: VoLTE_LIVE, PROFILE: VoLTE_LIVE) Failures occurs while inserted data in ElaticSearch : failure in bulk execution:\r\n> [3]: index [stc], type [campaign], id [324_966567885550], message [[stc][[stc][3]] VersionConflictEngineException[[campaign][324_966567885550]: version conflict, current [6], provided [5]]]\r\n\r\nWhat could be the issue. My running elastic search version is 2.3.2\r\n\r\nRegards,\r\nRajib\r\n\r\n","closed_by":{"login":"jasontedor","id":4744941,"node_id":"MDQ6VXNlcjQ3NDQ5NDE=","avatar_url":"https://avatars3.githubusercontent.com/u/4744941?v=4","gravatar_id":"","url":"https://api.github.com/users/jasontedor","html_url":"https://github.com/jasontedor","followers_url":"https://api.github.com/users/jasontedor/followers","following_url":"https://api.github.com/users/jasontedor/following{/other_user}","gists_url":"https://api.github.com/users/jasontedor/gists{/gist_id}","starred_url":"https://api.github.com/users/jasontedor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jasontedor/subscriptions","organizations_url":"https://api.github.com/users/jasontedor/orgs","repos_url":"https://api.github.com/users/jasontedor/repos","events_url":"https://api.github.com/users/jasontedor/events{/privacy}","received_events_url":"https://api.github.com/users/jasontedor/received_events","type":"User","site_admin":false},"performed_via_github_app":null}