[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/18403595","html_url":"https://github.com/elastic/elasticsearch/issues/3088#issuecomment-18403595","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/3088","id":18403595,"node_id":"MDEyOklzc3VlQ29tbWVudDE4NDAzNTk1","user":{"login":"philayres","id":294874,"node_id":"MDQ6VXNlcjI5NDg3NA==","avatar_url":"https://avatars0.githubusercontent.com/u/294874?v=4","gravatar_id":"","url":"https://api.github.com/users/philayres","html_url":"https://github.com/philayres","followers_url":"https://api.github.com/users/philayres/followers","following_url":"https://api.github.com/users/philayres/following{/other_user}","gists_url":"https://api.github.com/users/philayres/gists{/gist_id}","starred_url":"https://api.github.com/users/philayres/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/philayres/subscriptions","organizations_url":"https://api.github.com/users/philayres/orgs","repos_url":"https://api.github.com/users/philayres/repos","events_url":"https://api.github.com/users/philayres/events{/privacy}","received_events_url":"https://api.github.com/users/philayres/received_events","type":"User","site_admin":false},"created_at":"2013-05-24T13:07:44Z","updated_at":"2013-05-24T13:07:44Z","author_association":"NONE","body":"An additional note. I found this similar issue for another user: http://www.marshut.com/kpnht/problems-with-rabbitmq-river-90rc2.html that I think is unrelated to their RabbitMQ river, but is the same issue as I am seeing. No resolution over there apart from to unplug the river.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/18407584","html_url":"https://github.com/elastic/elasticsearch/issues/3088#issuecomment-18407584","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/3088","id":18407584,"node_id":"MDEyOklzc3VlQ29tbWVudDE4NDA3NTg0","user":{"login":"s1monw","id":973334,"node_id":"MDQ6VXNlcjk3MzMzNA==","avatar_url":"https://avatars0.githubusercontent.com/u/973334?v=4","gravatar_id":"","url":"https://api.github.com/users/s1monw","html_url":"https://github.com/s1monw","followers_url":"https://api.github.com/users/s1monw/followers","following_url":"https://api.github.com/users/s1monw/following{/other_user}","gists_url":"https://api.github.com/users/s1monw/gists{/gist_id}","starred_url":"https://api.github.com/users/s1monw/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/s1monw/subscriptions","organizations_url":"https://api.github.com/users/s1monw/orgs","repos_url":"https://api.github.com/users/s1monw/repos","events_url":"https://api.github.com/users/s1monw/events{/privacy}","received_events_url":"https://api.github.com/users/s1monw/received_events","type":"User","site_admin":false},"created_at":"2013-05-24T14:19:52Z","updated_at":"2013-05-24T14:19:52Z","author_association":"CONTRIBUTOR","body":"no matter why this happens it's bad to fail with a corrupt index (which is essentially what an exception during merge is) We should track down the race but first of all I think we should return the default postings format instead of failing with an exception\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/18449338","html_url":"https://github.com/elastic/elasticsearch/issues/3088#issuecomment-18449338","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/3088","id":18449338,"node_id":"MDEyOklzc3VlQ29tbWVudDE4NDQ5MzM4","user":{"login":"philayres","id":294874,"node_id":"MDQ6VXNlcjI5NDg3NA==","avatar_url":"https://avatars0.githubusercontent.com/u/294874?v=4","gravatar_id":"","url":"https://api.github.com/users/philayres","html_url":"https://github.com/philayres","followers_url":"https://api.github.com/users/philayres/followers","following_url":"https://api.github.com/users/philayres/following{/other_user}","gists_url":"https://api.github.com/users/philayres/gists{/gist_id}","starred_url":"https://api.github.com/users/philayres/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/philayres/subscriptions","organizations_url":"https://api.github.com/users/philayres/orgs","repos_url":"https://api.github.com/users/philayres/repos","events_url":"https://api.github.com/users/philayres/events{/privacy}","received_events_url":"https://api.github.com/users/philayres/received_events","type":"User","site_admin":false},"created_at":"2013-05-25T15:58:13Z","updated_at":"2013-05-25T15:58:13Z","author_association":"NONE","body":"Thanks for the incredibly fast response. \n\nI see from the commits we are now logging the issue rather than raising an exception. What effect does this have on the automatic creation of a new element in the mapping if we hit this condition? Do we just skip it, or is the mapping now updated accordingly? My concern is just that we would be arbitrarily not indexing elements in a document based on this error. Or is this not really an error condition and I'm misinterpreting?\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/18450136","html_url":"https://github.com/elastic/elasticsearch/issues/3088#issuecomment-18450136","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/3088","id":18450136,"node_id":"MDEyOklzc3VlQ29tbWVudDE4NDUwMTM2","user":{"login":"s1monw","id":973334,"node_id":"MDQ6VXNlcjk3MzMzNA==","avatar_url":"https://avatars0.githubusercontent.com/u/973334?v=4","gravatar_id":"","url":"https://api.github.com/users/s1monw","html_url":"https://github.com/s1monw","followers_url":"https://api.github.com/users/s1monw/followers","following_url":"https://api.github.com/users/s1monw/following{/other_user}","gists_url":"https://api.github.com/users/s1monw/gists{/gist_id}","starred_url":"https://api.github.com/users/s1monw/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/s1monw/subscriptions","organizations_url":"https://api.github.com/users/s1monw/orgs","repos_url":"https://api.github.com/users/s1monw/repos","events_url":"https://api.github.com/users/s1monw/events{/privacy}","received_events_url":"https://api.github.com/users/s1monw/received_events","type":"User","site_admin":false},"created_at":"2013-05-25T16:46:36Z","updated_at":"2013-05-25T16:46:36Z","author_association":"CONTRIBUTOR","body":"the condition you are seening is certainly not correc, the mapper for a given field is not present in the mapping which can have multiple reasons which I am trying to figure out at the moment. My suspicion is that due to some index deleting or type deletion the mappings are pruned and therefor a concurrently running merge can't access this mapping. So what happens if we return the default postings format rather than a per field format is in the worst case the default field format for the current lucene version you are using (which in your case is very likely identical). That won't be a problem since we pruned the mapper anyways so this field will likely not be accessed anymore. I am still trying to reproduce this but your docs will be updated correctly.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/18454227","html_url":"https://github.com/elastic/elasticsearch/issues/3088#issuecomment-18454227","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/3088","id":18454227,"node_id":"MDEyOklzc3VlQ29tbWVudDE4NDU0MjI3","user":{"login":"philayres","id":294874,"node_id":"MDQ6VXNlcjI5NDg3NA==","avatar_url":"https://avatars0.githubusercontent.com/u/294874?v=4","gravatar_id":"","url":"https://api.github.com/users/philayres","html_url":"https://github.com/philayres","followers_url":"https://api.github.com/users/philayres/followers","following_url":"https://api.github.com/users/philayres/following{/other_user}","gists_url":"https://api.github.com/users/philayres/gists{/gist_id}","starred_url":"https://api.github.com/users/philayres/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/philayres/subscriptions","organizations_url":"https://api.github.com/users/philayres/orgs","repos_url":"https://api.github.com/users/philayres/repos","events_url":"https://api.github.com/users/philayres/events{/privacy}","received_events_url":"https://api.github.com/users/philayres/received_events","type":"User","site_admin":false},"created_at":"2013-05-25T21:29:18Z","updated_at":"2013-05-25T21:29:18Z","author_association":"NONE","body":"Simon, I'd be happy to spin up a copy of this server so you can take a look directly at the mappings and data if that would help to reproduce this situation. Just let me know.\n\nJust in case it is useful, I spotted the field in question (entities.description.urls.display_url) potentially having its mapping set when the data being passed included a 'special' character. I don't know if the actual field value could affect the mapping creation. The data was a regular ascii string ending with an elipsis (hex E2 80 A6). This may be unrelated, it just seemed unusual.\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/18686285","html_url":"https://github.com/elastic/elasticsearch/issues/3088#issuecomment-18686285","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/3088","id":18686285,"node_id":"MDEyOklzc3VlQ29tbWVudDE4Njg2Mjg1","user":{"login":"ajhalani","id":1163503,"node_id":"MDQ6VXNlcjExNjM1MDM=","avatar_url":"https://avatars3.githubusercontent.com/u/1163503?v=4","gravatar_id":"","url":"https://api.github.com/users/ajhalani","html_url":"https://github.com/ajhalani","followers_url":"https://api.github.com/users/ajhalani/followers","following_url":"https://api.github.com/users/ajhalani/following{/other_user}","gists_url":"https://api.github.com/users/ajhalani/gists{/gist_id}","starred_url":"https://api.github.com/users/ajhalani/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ajhalani/subscriptions","organizations_url":"https://api.github.com/users/ajhalani/orgs","repos_url":"https://api.github.com/users/ajhalani/repos","events_url":"https://api.github.com/users/ajhalani/events{/privacy}","received_events_url":"https://api.github.com/users/ajhalani/received_events","type":"User","site_admin":false},"created_at":"2013-05-30T15:07:06Z","updated_at":"2013-05-30T15:07:06Z","author_association":"NONE","body":"This issue affected us for regular indexing as well. We suspect this was caused when in 0.20.x, we overwrote existing mapping with new mapping which had fewer fields. The data somehow still had the old fields and merge failed with 0.90.0.\nWith 0.90.1, we are now getting warnings but doesn't fail. thanks!\n","performed_via_github_app":null},{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/18686897","html_url":"https://github.com/elastic/elasticsearch/issues/3088#issuecomment-18686897","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/3088","id":18686897,"node_id":"MDEyOklzc3VlQ29tbWVudDE4Njg2ODk3","user":{"login":"s1monw","id":973334,"node_id":"MDQ6VXNlcjk3MzMzNA==","avatar_url":"https://avatars0.githubusercontent.com/u/973334?v=4","gravatar_id":"","url":"https://api.github.com/users/s1monw","html_url":"https://github.com/s1monw","followers_url":"https://api.github.com/users/s1monw/followers","following_url":"https://api.github.com/users/s1monw/following{/other_user}","gists_url":"https://api.github.com/users/s1monw/gists{/gist_id}","starred_url":"https://api.github.com/users/s1monw/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/s1monw/subscriptions","organizations_url":"https://api.github.com/users/s1monw/orgs","repos_url":"https://api.github.com/users/s1monw/repos","events_url":"https://api.github.com/users/s1monw/events{/privacy}","received_events_url":"https://api.github.com/users/s1monw/received_events","type":"User","site_admin":false},"created_at":"2013-05-30T15:15:14Z","updated_at":"2013-05-30T15:15:14Z","author_association":"CONTRIBUTOR","body":"cool thanks for reporting\n","performed_via_github_app":null}]