{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/31531","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/31531/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/31531/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/31531/events","html_url":"https://github.com/elastic/elasticsearch/issues/31531","id":334870300,"node_id":"MDU6SXNzdWUzMzQ4NzAzMDA=","number":31531,"title":"startObject \"details\" throws UncategorizedExecutionException  ES 6.3.0","user":{"login":"gmarshall56","id":5943189,"node_id":"MDQ6VXNlcjU5NDMxODk=","avatar_url":"https://avatars0.githubusercontent.com/u/5943189?v=4","gravatar_id":"","url":"https://api.github.com/users/gmarshall56","html_url":"https://github.com/gmarshall56","followers_url":"https://api.github.com/users/gmarshall56/followers","following_url":"https://api.github.com/users/gmarshall56/following{/other_user}","gists_url":"https://api.github.com/users/gmarshall56/gists{/gist_id}","starred_url":"https://api.github.com/users/gmarshall56/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gmarshall56/subscriptions","organizations_url":"https://api.github.com/users/gmarshall56/orgs","repos_url":"https://api.github.com/users/gmarshall56/repos","events_url":"https://api.github.com/users/gmarshall56/events{/privacy}","received_events_url":"https://api.github.com/users/gmarshall56/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-06-22T13:03:12Z","updated_at":"2018-06-22T15:57:37Z","closed_at":"2018-06-22T15:57:37Z","author_association":"NONE","active_lock_reason":null,"body":" Bug report\r\n\r\n**Elasticsearch version: 6.3.0\r\n\r\nPlugins installed: none\r\n\r\nJVM version: java version \"1.8.0_172\"\r\n\r\nOS version: Windows 10\r\n\r\nDescription of the problem including expected versus actual behavior:\r\nIncluding a startObject field with the name \"details\" in the \"properties\" of XContentBuilder results in a UncategorizedExecutionException to be thrown.\r\n\r\nSteps to reproduce:\r\nSee next.\r\n\r\nPlease include a *minimal* but *complete* recreation of the problem, including\r\n(e.g.) index creation, mappings, settings, query etc.  The easier you make for\r\nus to reproduce it, the more likely that somebody will take the time to look at it.\r\n\r\nHere is the code for the XContentBuilder we are instantiating( the \"...\" indicates there are more .startObject statements:\r\n` XContentBuilder builder = jsonBuilder().startObject()\r\n\t.startObject(RESOURCE_TYPE)\r\n\t\t.startObject(\"properties\")\r\n\t\t\t.startObject(\"details\").field(\"type\", \"string\").endObject()  <== causes exception\r\n\t\t\t.startObject(\"latlon\").field(\"type\", \"geo_point\").endObject()\r\n\t\t\t.startObject(\"path\").field(\"type\", \"text\").field(\"analyzer\", \"path-analyzer\").field(\"fielddata\", \r\n true).endObject()\r\n\t\t\t.startObject(\"emailString\").field(\"type\", \"text\").field(\"analyzer\", \"url-email-analyzer\").endObject()\r\n\t\t\t... \t\r\n\t\t.endObject()\r\n\t.endObject().endObject();`\r\n\r\nProvide logs:\r\nHaving that `.startObject(\"details\").field(\"type\", \"string\").endObject()` defined in the XContentBuilder throws this exception when the code is executed:\r\n> UncategorizedExecutionException[Failed execution]; nested: IOException[Duplicate field 'details'\r\n at [Source: java.io.StringReader@e455a7c; line: 1, column: 616]];\r\n\tat org.elasticsearch.common.util.concurrent.FutureUtils.rethrowExecutionException(FutureUtils.java:90)\r\n\tat org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:55)\r\n\tat org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:34)\r\n...\r\n...\r\n<\r\nWhen the `.startObject(\"details\").field(\"type\", \"string\").endObject()` is commented out there is no exception thrown.\r\n\r\nWe have had the XContentBuilder defined as you see here for quite some time now without any issues.  With ES version 6.3.0 I am now getting this exception.  Please advise:  Can we no longer define a \"details\" field defined in ES version 6.3.0?  Or should this \"details\" filed be defined in the .startObject in another way?\r\nThank you for your time.\r\n","closed_by":{"login":"martijnvg","id":580421,"node_id":"MDQ6VXNlcjU4MDQyMQ==","avatar_url":"https://avatars3.githubusercontent.com/u/580421?v=4","gravatar_id":"","url":"https://api.github.com/users/martijnvg","html_url":"https://github.com/martijnvg","followers_url":"https://api.github.com/users/martijnvg/followers","following_url":"https://api.github.com/users/martijnvg/following{/other_user}","gists_url":"https://api.github.com/users/martijnvg/gists{/gist_id}","starred_url":"https://api.github.com/users/martijnvg/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/martijnvg/subscriptions","organizations_url":"https://api.github.com/users/martijnvg/orgs","repos_url":"https://api.github.com/users/martijnvg/repos","events_url":"https://api.github.com/users/martijnvg/events{/privacy}","received_events_url":"https://api.github.com/users/martijnvg/received_events","type":"User","site_admin":false},"performed_via_github_app":null}