[{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/comments/425016981","html_url":"https://github.com/elastic/elasticsearch/issues/34098#issuecomment-425016981","issue_url":"https://api.github.com/repos/elastic/elasticsearch/issues/34098","id":425016981,"node_id":"MDEyOklzc3VlQ29tbWVudDQyNTAxNjk4MQ==","user":{"login":"cbuescher","id":10398885,"node_id":"MDQ6VXNlcjEwMzk4ODg1","avatar_url":"https://avatars0.githubusercontent.com/u/10398885?v=4","gravatar_id":"","url":"https://api.github.com/users/cbuescher","html_url":"https://github.com/cbuescher","followers_url":"https://api.github.com/users/cbuescher/followers","following_url":"https://api.github.com/users/cbuescher/following{/other_user}","gists_url":"https://api.github.com/users/cbuescher/gists{/gist_id}","starred_url":"https://api.github.com/users/cbuescher/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/cbuescher/subscriptions","organizations_url":"https://api.github.com/users/cbuescher/orgs","repos_url":"https://api.github.com/users/cbuescher/repos","events_url":"https://api.github.com/users/cbuescher/events{/privacy}","received_events_url":"https://api.github.com/users/cbuescher/received_events","type":"User","site_admin":false},"created_at":"2018-09-27T09:07:06Z","updated_at":"2018-09-27T09:07:06Z","author_association":"MEMBER","body":"@s1monw thanks, this should have been muted in the commit as well (the test was already borked but didn't throw the exception that we get now). Somehow this slipped CI due to lucky randomization. This is probably best handled as part of https://github.com/elastic/elasticsearch/issues/34046 since it is a similar issue. I will close this in favour of https://github.com/elastic/elasticsearch/issues/34046 and update the @AwaitsFix accordingly.","performed_via_github_app":null}]