{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/52501","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/52501/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/52501/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/52501/events","html_url":"https://github.com/elastic/elasticsearch/issues/52501","id":567384262,"node_id":"MDU6SXNzdWU1NjczODQyNjI=","number":52501,"title":"Getting elasticsearch connection error.","user":{"login":"manasatmicro","id":57709441,"node_id":"MDQ6VXNlcjU3NzA5NDQx","avatar_url":"https://avatars0.githubusercontent.com/u/57709441?v=4","gravatar_id":"","url":"https://api.github.com/users/manasatmicro","html_url":"https://github.com/manasatmicro","followers_url":"https://api.github.com/users/manasatmicro/followers","following_url":"https://api.github.com/users/manasatmicro/following{/other_user}","gists_url":"https://api.github.com/users/manasatmicro/gists{/gist_id}","starred_url":"https://api.github.com/users/manasatmicro/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/manasatmicro/subscriptions","organizations_url":"https://api.github.com/users/manasatmicro/orgs","repos_url":"https://api.github.com/users/manasatmicro/repos","events_url":"https://api.github.com/users/manasatmicro/events{/privacy}","received_events_url":"https://api.github.com/users/manasatmicro/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2020-02-19T08:00:01Z","updated_at":"2020-02-19T09:04:23Z","closed_at":"2020-02-19T09:04:22Z","author_association":"NONE","active_lock_reason":null,"body":"> Failed to query Elasticsearch using 'status:(*\"Live\"*)': ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1fe5de4668>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1fe5de4668>: Failed to establish a new connection: [Errno 111] Connection refused)\r\nTraceback (most recent call last):\r\n  File \"/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/urllib3/connection.py\", line 157, in _new_conn\r\n    (self._dns_host, self.port), self.timeout, **extra_kw\r\n  File \"/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/urllib3/util/connection.py\", line 84, in create_connection\r\n    raise err\r\n  File \"/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/urllib3/util/connection.py\", line 74, in create_connection\r\n    sock.connect(sa)\r\nConnectionRefusedError: [Errno 111] Connection refused\r\nDuring handling of the above exception, another exception occurred\r\nTraceback (most recent call last):\r\n  File \"/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 74, in perform_request\r\n\r\n\r\nI got above error when i run the project i have elasticsearch version 6.8 installed in my system. Since 3 days i tried almost each method i found in google but it did not helped.\r\n ","closed_by":{"login":"ywelsch","id":3718355,"node_id":"MDQ6VXNlcjM3MTgzNTU=","avatar_url":"https://avatars3.githubusercontent.com/u/3718355?v=4","gravatar_id":"","url":"https://api.github.com/users/ywelsch","html_url":"https://github.com/ywelsch","followers_url":"https://api.github.com/users/ywelsch/followers","following_url":"https://api.github.com/users/ywelsch/following{/other_user}","gists_url":"https://api.github.com/users/ywelsch/gists{/gist_id}","starred_url":"https://api.github.com/users/ywelsch/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ywelsch/subscriptions","organizations_url":"https://api.github.com/users/ywelsch/orgs","repos_url":"https://api.github.com/users/ywelsch/repos","events_url":"https://api.github.com/users/ywelsch/events{/privacy}","received_events_url":"https://api.github.com/users/ywelsch/received_events","type":"User","site_admin":false},"performed_via_github_app":null}