{"url":"https://api.github.com/repos/elastic/elasticsearch/issues/9173","repository_url":"https://api.github.com/repos/elastic/elasticsearch","labels_url":"https://api.github.com/repos/elastic/elasticsearch/issues/9173/labels{/name}","comments_url":"https://api.github.com/repos/elastic/elasticsearch/issues/9173/comments","events_url":"https://api.github.com/repos/elastic/elasticsearch/issues/9173/events","html_url":"https://github.com/elastic/elasticsearch/issues/9173","id":53567532,"node_id":"MDU6SXNzdWU1MzU2NzUzMg==","number":9173,"title":"Bulk API changed behavior for status code","user":{"login":"matthughes","id":173132,"node_id":"MDQ6VXNlcjE3MzEzMg==","avatar_url":"https://avatars1.githubusercontent.com/u/173132?v=4","gravatar_id":"","url":"https://api.github.com/users/matthughes","html_url":"https://github.com/matthughes","followers_url":"https://api.github.com/users/matthughes/followers","following_url":"https://api.github.com/users/matthughes/following{/other_user}","gists_url":"https://api.github.com/users/matthughes/gists{/gist_id}","starred_url":"https://api.github.com/users/matthughes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/matthughes/subscriptions","organizations_url":"https://api.github.com/users/matthughes/orgs","repos_url":"https://api.github.com/users/matthughes/repos","events_url":"https://api.github.com/users/matthughes/events{/privacy}","received_events_url":"https://api.github.com/users/matthughes/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2015-01-06T21:46:05Z","updated_at":"2015-01-13T19:21:54Z","closed_at":"2015-01-13T19:21:54Z","author_association":"CONTRIBUTOR","active_lock_reason":null,"body":"At least as far back as 1.3.5, if a _bulk operation had any errors, it would return the most severe error as the HTTP status code.  This changed at least in 1.4.2.  \n\nI have auto_index_create turned off for my indexes:\n\n```\nbash-4.1# cat request.txt\n{ \"index\" : { \"_index\" : \"myindex\", \"_type\" : \"type1\", \"_id\" : \"1\" } }\n{ \"field1\" : \"value1\" }\n\n\nbash-4.1# curl -v XPUT http://localhost:9200/myindex/event/_bulk --data-binary @request.txt; echo\n* getaddrinfo(3) failed for XPUT:80\n* Couldn't resolve host 'XPUT'\n* Closing connection #0\ncurl: (6) Couldn't resolve host 'XPUT'\n* About to connect() to localhost port 9200 (#0)\n*   Trying ::1... connected\n* Connected to localhost (::1) port 9200 (#0)\n> POST /myindex/event/_bulk HTTP/1.1\n> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2\n> Host: localhost:9200\n> Accept: */*\n> Content-Length: 113\n> Content-Type: application/x-www-form-urlencoded\n>\n< HTTP/1.1 200 OK\n< Content-Type: application/json; charset=UTF-8\n< Content-Length: 187\n<\n* Connection #0 to host localhost left intact\n* Closing connection #0\n{\"took\":1,\"errors\":true,\"items\":[{\"index\":{\"_index\":\"myindex\",\"_type\":\"type1\",\"_id\":\"1\",\"status\":404,\"error\":\"IndexMissingException[[myindex] missing]\"}}]}\n```\n\nIn 1.3.5 and below I could always count on the HTTP status code being 404 from this call.  Was this an intentional change in behavior?  It looks like it might be related to changes from this issue: #8125\n","closed_by":{"login":"clintongormley","id":56599,"node_id":"MDQ6VXNlcjU2NTk5","avatar_url":"https://avatars0.githubusercontent.com/u/56599?v=4","gravatar_id":"","url":"https://api.github.com/users/clintongormley","html_url":"https://github.com/clintongormley","followers_url":"https://api.github.com/users/clintongormley/followers","following_url":"https://api.github.com/users/clintongormley/following{/other_user}","gists_url":"https://api.github.com/users/clintongormley/gists{/gist_id}","starred_url":"https://api.github.com/users/clintongormley/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/clintongormley/subscriptions","organizations_url":"https://api.github.com/users/clintongormley/orgs","repos_url":"https://api.github.com/users/clintongormley/repos","events_url":"https://api.github.com/users/clintongormley/events{/privacy}","received_events_url":"https://api.github.com/users/clintongormley/received_events","type":"User","site_admin":false},"performed_via_github_app":null}